### PR TITLE
Make HoloPy build on Windows with conda-forge

### PR DESCRIPTION
**Pull request by barkls**
conda-forge can now use [flang](https://github.com/flang-compiler/flang) to compile Fortran on Windows. This PR includes 3 changes to make HoloPy build in this environment:

1) Switch (revert) to using double precision axisymmetric T-matrix code. The flang compiler doesn't support quad-precision variables so we have to switch back to double precision, which I salvaged from an old PR.

2) Removal of mie_f/scfodim.for parameter file for multisphere since Fortran's ``include`` command wasn't finding it. There are several degrees of separation between us and what is actually doing the compile, since it goes through conda-forge's machinery and also f2py, so it's not easy to add a flag when calling the compiler to help find the file. I just pasted the file contents everywhere we were supposed to include it. Note that this file doesn't allow us to easily change parameters anyway, see #88 comments thread.

3) Let setup.py bypass compiling Tmatrix code. Our Makefile has gfortran hard-coded, but flang is a separate compiler. I can compile Tmatrix code with a ``bld.bat`` file independent of setup.py that will run only on conda-forge.

### CODE REVIEW

**Comment by barkls** [comment]
The failing test on Travis is a Multisphere failure, see #194. All tests passed locally.

**Comment by vnmanoharan** [comment]
Excellent!  Well done.  I wonder if we can put these changes in a different branch and tell conda-forge to compile the windows package from that branch.  I would like to keep quad precision for linux and mac, since it might be needed to handle axisymmetric objects with high aspect ratios.

**Comment by barkls** [comment]
I'm not certain, but I expect building from two separate branches is possible with conda-forge. However, I'm not sure that is the best approach, since we would then have to merge all future changes into both branches. An alternative would be to distribute both versions of the Fortran code (approx. 180 kB each) and compile the appropriate version in each case.

**Comment by vnmanoharan** [comment]
I don't think merging will be a big problem, since most of the edits are to files that don't get changed much. So merging changes to a windows-build branch from the master branch should rarely give conflicts.

**Comment by barkls** [comment]
Ok I've changed this PR to merge into a new branch. It is worth clarifying in the docs that users trying to build from source on windows should clone master, and not windows-build (which now lacks a T-matrix Makefile - maybe I should just put it back?)...

**Comment by tdimiduk** [comment]
Is there not a way to something with preprocessor directives and makefiles
to that will work on windows but also give the precision we want on linux?
Or by having a small fortran file that controls the precision that we build
against different versions on windows and linux? Or (this may be a really
bad idea) have a setup.py script which modifies the code when building on
windows to the needed precision before building? From what I have absorbed
of packaging wisdom from open source communities, I think if there is some
way to use the same codebase without significant code duplication, that
might be preferable.

**Comment by vnmanoharan** [comment]
@barkls I think it's fine to leave the makefile out of windows-build. To advise users on which branch to use for building, I recommend modifying the README.md file, since that advice is specific to GitHub. 

We should also update the docs to describe building on Windows with gfortran.  Pinging @ralex0 here to help with that task.

**Comment by vnmanoharan** [comment]
@tdimiduk The master branch compiles fine on any platform with gfortran, including windows.  The only issue is that conda-forge can't compile with gfortran, so the branch would only be used in conda-forge's automated builds of conda packages.  The master branch will remain usable and compile-able on all platforms.

**Comment by barkls** [comment]
The docs currently do have instructions that @ralex0 put together for compiling on Windows with gfortran.

Are we set to merge? (Failing Travis is still due to #194)

**Comment by tdimiduk** [comment]
Ah, that is probably reasonable then. There is value to having a single
codebase for all platforms (which I am comfortable calling conda-forge a
platform here), but you are probably right that it isn't worth complicating
things for that, people do release branches and backport things all the
time and this looks like it will be simpler than that.

**Comment by vnmanoharan** [comment]
I will merge. @barkls, could you please file an issue saying that quad-precision compilation and includes don't work with flang? That will address @tdimiduk's point about flang not working as a platform with master.  We may be able to fix this in the future.  Also please file an update to #142, which I think is OK to close now.

**Pull request merged**
