### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by barkls**
Supersedes #334 and also cleans up test import structure

### CODE REVIEW

**Comment by barkls** [comment]
removing the test init files will prevent sphinx apidoc from building files for the test directories since they won't be treated as submodules any more. Tests pass with them removed, but there might be unintended consequences, such as files not getting carried around by conda. I don't think anyone is trying to run tests of a conda distribution though, and inference tests never had __init__.py to begin with.

**Comment by barkls** [comment]
I don't think we want to have the tests in the HoloPy namespace. Is there a use case for importing test code (including common) when you can't just run the file directly? I see imports as being useful when you want to be able to run the code but not edit it, and I'm not sure when this would ever apply to tests.

That being said, I don't feel strongly about it and we can certainly put the __init__ files back in, which could also have the side-effect of resolving #342. Currently things are inconsistent with some test directories having an `__init__.py` and others not, so we could apply a standard either way.

**Comment by briandleahy** [comment]
Sounds good. We can always change it back if we want later. 

Merging this in now.

**Comment by briandleahy** [comment]
Thanks @barkls . I thought I dismissed them myself earlier.

**Pull request merged**
