### PR TITLE
V3

### PR DESCRIPTION
**Pull request by barkls**

### CODE REVIEW

**Comment by tdimiduk** [comment]
I am not sure we want to add the full_data files to the setup script. They are mostly for us in development to increase confidence, but I don't think we need to ship them with builds.

Also what are the changes to the binary files recon_*.npy?

**Comment by barkls** [comment]
sorry for the confusion. This is a duplicate of PR#92 with one additional commit to fix a test that didn't get merged correctly.

**Comment by barkls** [comment]
recon_*.npy aren't used by anything anymore.

**Comment by barkls** [comment]
I agree we don't need to ship full_data files in setup script. I will revert that in my next PR.

**Pull request merged**
