### PR TITLE
windows installation docs

### PR DESCRIPTION
**Pull request by barkls**
It might be better to create a manoharan-lab conda channel.

### CODE REVIEW

**Comment by vnmanoharan** [comment]
Since the channel might change (and we might eventually get conda-forge working), perhaps its best for now to just say that the easiest way to install on windows is to search for a package using `anaconda search holopy` and install that.  I think the docs are the place to put specific info about how to build holopy and general info about how to install binaries (since our methods for producing binaries might change rapidly). The most appropriate place for describing how to install binaries might be in the README.rst

**Comment by barkls** [comment]
I agree it would be nice to not have to update docs whenever we change distribution, so maybe that's not the best place to put it. I'm not sure the readme is a good choice either though, since we want to include specific technical instructions for installing binaries on windows. My interpretation of the readme is that it should be a general entry point to HoloPy for all users. We do have an older file called ``INSTALL.txt`` that hasn't been updated in a while (but is still accurate). That seems like a logical place to put detailed installation instructions.

**Comment by vnmanoharan** [comment]
I don't think INSTALL.txt is the place to put this info, because it's not easily accessible by the web.  There are three webpages where people can get introduced to HoloPy:

1) http://holopy.readthedocs.io/en/master/
2) https://github.com/manoharan-lab/holopy
3) http://manoharan.seas.harvard.edu/holopy

I think (1) should just have a statement about using `anaconda search holopy` and then installing from whatever channel that reports.  Right now, it reports that ralex0 has the win64 binaries and conda-forge for linux and macos.  But I don't htink we should add the channel name to the documentation, since that will likely change.

(2) points to the README.rst, which is not a bad place to put the instructions for installation, or at least a link to the relevant page in the manual.

(3) might be used to give more specific information about which channel to use.  But I think it is sufficient to update (1) with the instructions (generic for all platforms) to do `anaconda search holopy`.

**Comment by barkls** [comment]
I agree that INSTALL.txt is not very accessible. I don't really see the purpose of this file anymore. It does not contain any information that cannot be found in the more accessible documentation.

I updated the docs to tell users to just do ``anaconda search holopy`` and go from there. The instructions are general and won't need to change with future updates to HoloPy or distribution. However, I disagree with this approach because we spent a long time trying to match versions of python and numpy. I think we should provide potential users with the specific information they need to reproduce the build environment. Maybe there's a way to specify this information when uploading to a conda channel?

**Comment by vnmanoharan** [comment]
But this is what dependencies are for. The conda packages need to specify what minimum version of python, numpy, and xarray they will work with.

**Comment by barkls** [comment]
I think there are two different sets of dependencies here. 

HoloPy has a set of dependencies, eg. python 3 & np>=1.12.

My understanding is that a built distribution has a more specific set of requirements, eg. python 3.6 and np=1.13 to reproduce the environment where it was compiled. I thought this was problem in #181. I don't know of a way to get these specific requirements from the conda package unless it has a different set of dependencies than HoloPy itself.

**Comment by vnmanoharan** [comment]
I mean the dependencies in the holopy conda package.  If I try to install a package from a conda channel, and (say) that package requires numpy 1.13 or higher, conda tries to figure out a solution to satisfy all the dependencies of the package I'm installing and the ones I already have. So conda is built to solve exactly this problem. We just need to make sure that the packages have the correct dependencies.

**Comment by vnmanoharan** [comment]
Or, if the conda package inherits these dependencies from HoloPy, we should just update the HoloPy package.  That means we would require python 3.6 and numpy >= 1.13.

**Comment by barkls** [comment]
Well no, that is only a requirement for a specific Windows built
distribution. I think the solution is for Ron to specify additional
dependencies when building a conda package on Windows to exactly replicate
his build environment. Ideally we would have Windows builds available for
multiple versions of python and numpy. For example, the requirement
wouldn't be np>=1.13. It would be np=1.13 for a particular Windows build
only.

**Comment by vnmanoharan** [comment]
Whatever the `np=` criterion, this is a problem that conda is meant to solve, and we should make the packages so that conda can solve it.

**Comment by vnmanoharan** [comment]
The term "built distribution" is confusing to me.  I would call it a "conda package" unless you mean something different.

**Pull request merged**
