### PR TITLE
Docs versioning

### PR DESCRIPTION
**Pull request by barkls**

### CODE REVIEW

**Comment by barkls** [comment]
Yes, it probably should. Unfortunately it looks like some recent merges
were made to the master branch as well, so there will need to be some
resolution at some point.

**Comment by vnmanoharan** [comment]
Suggest that we backport these changes to master, update the version number to 3.1.2 (in master), and release 3.1.2.

**Comment by barkls** [comment]
Unfortunately the tests on Travis are not currently passing on the master
branch (see PR #210), so I don't think we should release it.

**Comment by vnmanoharan** [comment]
Travis log says it's the doctest in the inference tutorial that's failing. This is directly related to #210 :
```
Document: users/infer_tutorial

------------------------------

**********************************************************************

File "users/infer_tutorial.rst", line 365, in default

Failed example:

    model = AlphaModel(spheres, noise_sd=noise_sd, alpha=1)

Exception raised:

    Traceback (most recent call last):

      File "/home/travis/miniconda3/envs/testenv/lib/python3.4/doctest.py", line 1318, in __run

        compileflags, 1), test.globs)

      File "<doctest default[0]>", line 1, in <module>

        model = AlphaModel(spheres, noise_sd=noise_sd, alpha=1)

    NameError: name 'noise_sd' is not defined

/home/travis/miniconda3/envs/testenv/lib/python3.4/site-packages/emcee/ensemble.py:335: RuntimeWarning: invalid value encountered in subtract

  lnpdiff = (self.dim - 1.) * np.log(zz) + newlnprob - lnprob0

/home/travis/miniconda3/envs/testenv/lib/python3.4/site-packages/emcee/ensemble.py:336: RuntimeWarning: invalid value encountered in greater

  accept = (lnpdiff > np.log(self._random.rand(len(lnpdiff))))
```

**Comment by barkls** [comment]
Indeed you are correct. The PR failed running nosetests on Travis ([Travis Build #463](https://travis-ci.org/manoharan-lab/holopy/builds/287564053)) due to an unknown bug, so it never ran doctests on the changed code. Upon merging, identical code passed nosetests ([Travis build #464](https://travis-ci.org/manoharan-lab/holopy/builds/287917118)), revealing a failure in the doctests. I'll try to sort this out and release a clean 3.1.2.

**Pull request merged**
