### PR TITLE
V3.1

### PR DESCRIPTION
**Pull request by barkls**

### CODE REVIEW

**Comment by vnmanoharan** [comment]
This looks good, but please wrap code to 79 characters and docstrings to 72, per PEP 8 and our own conventions.

**Comment by barkls** [comment]
Which files do you mean?

**Comment by vnmanoharan** [comment]
`pylint holopy.scattering`
`pylint holopy.scattering.theory`
`pylint holopy`

**Comment by barkls** [comment]
The worst offenders seemed to be the indicator functions that Anna wrote to describe DDA scatterers.

**Pull request merged**
