### PR TITLE
Emcee3

### PR DESCRIPTION
**Pull request by ralex0**
This PR 
- fixes the deprecation warnings triggered by emcee's 3.0 API changes
- fixes the two MCMC tests that have been failing for some of us.
- changes some of travis's pinnings per #299
- closes #308, but I've already done that 😉

### CODE REVIEW

**Comment by barkls** [comment]
Hey @ralex0, thanks for switching this over. There are a bunch of unresolved merge conflicts in some of the files. They're not in files you were modifying, so the easiest thing is probably to just apply your changes on top of the rebase branch. Going through and fixing the merge conflicts will make everyone's life easier in future though!

**Comment by ralex0** [comment]
Let me try to fix the merge conflicts. 

It's weird cause the Github Bot is saying I can merge this without conflicts!

**Comment by barkls** [comment]
Yes, you could, but the files are full of git merge nonsense!

**Comment by ralex0** [comment]
Ok I just redid the commits in #310

**Pull request closed without merging**
